/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // sidebar: [{ type: 'autogenerated', dirName: '.' }]
  sidebar: [
    {
      type: 'doc',
      id: 'main'
    },
    {
      type: 'category',
      label: 'Правовые документы',
      items: [
        {
          type: 'doc',
          id: 'rules'
        },
        {
          type: 'doc',
          id: 'confidential'
        }
      ]
    }
  ]
};

module.exports = sidebars;
